version: 2
updates:
  # Python依存関係の自動更新（本番依存関係）
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"  # セキュリティ更新を迅速に検出
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 15
    reviewers:
      - "scottlz0310"
    assignees:
      - "scottlz0310"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    # セキュリティ更新の優先度設定
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # 脆弱性のあるパッケージは即座に更新
    security-updates:
      enabled: true
    # バージョニング戦略
    versioning-strategy: "increase"
    # セキュリティ更新とパッチ/マイナー更新の優先度設定
    groups:
      critical-security:
        patterns:
          - "*"
        update-types:
          - "security"
        priority: 10
        # 重要なセキュリティ依存関係
        dependency-type: "all"
      core-dependencies:
        patterns:
          - "requests*"
          - "urllib3*"
          - "cryptography*"
          - "pyjwt*"
        update-types:
          - "security"
          - "patch"
          - "minor"
        priority: 9
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
        priority: 5
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
        priority: 3
    # 無視する依存関係（メジャーバージョンアップは手動確認）
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # 重要なセキュリティ依存関係の特別扱い
    rebase-strategy: "auto"

  # GitHub Actions依存関係の自動更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "scottlz0310"
    assignees:
      - "scottlz0310"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    # セキュリティ更新の優先度設定
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # セキュリティ更新の即座対応
    security-updates:
      enabled: true
    # GitHub Actionsのセキュリティ更新グループ
    groups:
      security-actions:
        patterns:
          - "*"
        update-types:
          - "security"
        priority: 10
    # バージョニング戦略
    versioning-strategy: "increase"
    rebase-strategy: "auto"

  # 開発依存関係の個別管理（テスト・リンティングツール）
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 8
    reviewers:
      - "scottlz0310"
    assignees:
      - "scottlz0310"
    commit-message:
      prefix: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "development"
    # 開発依存関係のみ対象
    allow:
      - dependency-type: "development"
    # セキュリティ更新は即座に対応
    security-updates:
      enabled: true
    # 開発ツールのグループ化
    groups:
      dev-security:
        patterns:
          - "*"
        update-types:
          - "security"
        priority: 8
      testing-tools:
        patterns:
          - "pytest*"
          - "coverage*"
          - "*test*"
        update-types:
          - "patch"
          - "minor"
        priority: 5
      linting-tools:
        patterns:
          - "ruff*"
          - "mypy*"
          - "black*"
          - "isort*"
        update-types:
          - "patch"
          - "minor"
        priority: 5
    # バージョニング戦略
    versioning-strategy: "increase"
    rebase-strategy: "auto"
