# Dependency Review設定
# GitHub Advanced Securityのdependency-review-actionで使用

# 脆弱性の重要度設定
fail_on_severity: 'moderate'

# 許可するライセンス
allow_licenses:
  - 'MIT'
  - 'Apache-2.0'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'ISC'
  - 'MPL-2.0'
  - 'Python Software Foundation License'

# 禁止するライセンス
deny_licenses:
  - 'GPL-2.0'
  - 'GPL-3.0'
  - 'AGPL-3.0'
  - 'LGPL-2.1'
  - 'LGPL-3.0'

# 除外するパッケージ（開発依存関係など）
exclude_scopes:
  - 'development'
  - 'runtime'

# 脆弱性スコア閾値
fail_on_scopes:
  - 'runtime'
  - 'development'

# コメント設定
comment_summary_in_pr: true
