"""Application settings using Pydantic Settings."""

import os
import subprocess
import tomllib
from functools import lru_cache
from pathlib import Path
from typing import Any, Self

from pydantic import Field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


def get_config_path() -> Path:
    """Get the configuration file path.

    Returns:
        Path to ~/.config/setup-repo/config.toml
    """
    return Path.home() / ".config" / "setup-repo" / "config.toml"


def load_config_file() -> dict[str, Any]:
    """Load configuration from TOML file if it exists.

    Returns:
        Dictionary with configuration values, or empty dict if file doesn't exist
    """
    config_path = get_config_path()
    if not config_path.exists():
        return {}

    try:
        with config_path.open("rb") as f:
            return tomllib.load(f)
    except (OSError, tomllib.TOMLDecodeError):
        return {}


def save_config(
    config_path: Path,
    *,
    github_owner: str,
    github_token: str | None,
    workspace_dir: Path,
    max_workers: int,
    use_https: bool,
    git_ssl_no_verify: bool,
    log_file: Path | None,
    auto_prune: bool,
    auto_stash: bool,
    auto_cleanup: bool,
    auto_cleanup_include_squash: bool,
) -> None:
    """Save configuration to TOML file.

    Args:
        config_path: Path to save the configuration
        github_owner: GitHub owner/organization name
        github_token: GitHub personal access token
        workspace_dir: Directory for cloning repositories
        max_workers: Number of parallel workers
        use_https: Use HTTPS for cloning instead of SSH
        git_ssl_no_verify: Disable SSL verification
        log_file: Path to log file (None to disable)
        auto_prune: Enable auto prune on pull
        auto_stash: Enable auto stash on pull
        auto_cleanup: Enable auto cleanup after sync
        auto_cleanup_include_squash: Include squash-merged branches for auto cleanup
    """
    config_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Setup Repository Configuration",
        "# Generated by 'setup-repo init'",
        "",
        "[github]",
        f'owner = "{github_owner}"',
    ]

    if github_token:
        lines.append(f'token = "{github_token}"')

    # Use as_posix() for cross-platform path format in TOML config
    lines.extend(
        [
            "",
            "[workspace]",
            f'dir = "{workspace_dir.as_posix()}"',
            f"max_workers = {max_workers}",
            "",
            "[git]",
            f"use_https = {str(use_https).lower()}",
            f"ssl_no_verify = {str(git_ssl_no_verify).lower()}",
            f"auto_prune = {str(auto_prune).lower()}",
            f"auto_stash = {str(auto_stash).lower()}",
            f"auto_cleanup = {str(auto_cleanup).lower()}",
            f"auto_cleanup_include_squash = {str(auto_cleanup_include_squash).lower()}",
            "",
            "[logging]",
        ]
    )

    if log_file:
        lines.append(f'file = "{log_file.as_posix()}"')
    else:
        lines.append('# file = "~/.local/share/setup-repo/logs/setup-repo.jsonl"')

    lines.append("")

    config_path.write_text("\n".join(lines), encoding="utf-8")


class AppSettings(BaseSettings):
    """Application settings with environment variable support."""

    model_config = SettingsConfigDict(
        env_prefix="SETUP_REPO_",
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # GitHub settings
    github_owner: str = Field(default="", description="GitHub owner name")
    github_token: str | None = Field(default=None, description="GitHub Token")
    use_https: bool = Field(default=False, description="Use HTTPS for cloning")

    # Directory settings
    workspace_dir: Path = Field(
        default=Path.home() / "workspace",
        description="Directory to clone repositories",
    )

    # Parallel processing settings
    max_workers: int = Field(default=10, ge=1, le=32, description="Number of parallel workers")

    # Git settings
    auto_prune: bool = Field(default=True, description="Auto fetch --prune")
    auto_stash: bool = Field(default=False, description="Auto stash/pop on pull")
    git_ssl_no_verify: bool = Field(default=False, description="Skip SSL verification (for internal CA)")
    auto_cleanup: bool = Field(default=False, description="Auto cleanup merged branches after sync")
    auto_cleanup_include_squash: bool = Field(
        default=False,
        description="Include squash-merged branches in auto cleanup",
    )

    # Logging settings
    log_level: str = Field(default="INFO", description="Log level")
    log_file: Path | None = Field(default=None, description="Log file path")

    @model_validator(mode="after")
    def load_config_and_auto_detect(self) -> Self:
        """Load config from TOML file and auto-detect settings if not provided."""
        # Load from TOML config file
        config = load_config_file()
        if config:
            self._apply_toml_config(config)

        # Auto-detect github_owner if still empty
        if not self.github_owner:
            if owner := os.environ.get("GITHUB_USER"):
                self.github_owner = owner
            else:
                try:
                    result = subprocess.run(
                        ["git", "config", "user.name"],
                        capture_output=True,
                        text=True,
                        timeout=5,
                    )
                    if result.returncode == 0:
                        self.github_owner = result.stdout.strip()
                except (subprocess.SubprocessError, OSError):
                    # Git command failed - owner remains empty
                    pass

        # Auto-detect github_token if still None
        if not self.github_token:
            try:
                result = subprocess.run(
                    ["gh", "auth", "token"],
                    capture_output=True,
                    text=True,
                    timeout=5,
                )
                if result.returncode == 0:
                    self.github_token = result.stdout.strip()
            except (subprocess.SubprocessError, OSError):
                # gh command failed - token remains None
                pass

        return self

    def _apply_toml_config(self, config: dict[str, Any]) -> None:
        """Apply settings from TOML config dictionary.

        Only applies TOML values for fields that were NOT set via environment variables.
        Environment variables always take precedence over TOML config.

        Args:
            config: Parsed TOML configuration
        """

        def _env_not_set(env_name: str) -> bool:
            """Check if environment variable is not set."""
            return os.environ.get(f"SETUP_REPO_{env_name}") is None

        # GitHub settings
        if github := config.get("github"):
            if (owner := github.get("owner")) and _env_not_set("GITHUB_OWNER"):
                self.github_owner = owner
            if (token := github.get("token")) and _env_not_set("GITHUB_TOKEN"):
                self.github_token = token

        # Workspace settings
        if workspace := config.get("workspace"):
            if (dir_str := workspace.get("dir")) and _env_not_set("WORKSPACE_DIR"):
                self.workspace_dir = Path(dir_str).expanduser()
            if (workers := workspace.get("max_workers")) and _env_not_set("MAX_WORKERS"):
                self.max_workers = workers

        # Git settings
        if git := config.get("git"):
            if "use_https" in git and _env_not_set("USE_HTTPS"):
                self.use_https = git["use_https"]
            if "ssl_no_verify" in git and _env_not_set("GIT_SSL_NO_VERIFY"):
                self.git_ssl_no_verify = git["ssl_no_verify"]
            if "auto_prune" in git and _env_not_set("AUTO_PRUNE"):
                self.auto_prune = git["auto_prune"]
            if "auto_stash" in git and _env_not_set("AUTO_STASH"):
                self.auto_stash = git["auto_stash"]
            if "auto_cleanup" in git and _env_not_set("AUTO_CLEANUP"):
                self.auto_cleanup = git["auto_cleanup"]
            if "auto_cleanup_include_squash" in git and _env_not_set("AUTO_CLEANUP_INCLUDE_SQUASH"):
                self.auto_cleanup_include_squash = git["auto_cleanup_include_squash"]

        # Logging settings
        if logging := config.get("logging"):
            if (file_str := logging.get("file")) and _env_not_set("LOG_FILE"):
                self.log_file = Path(file_str).expanduser()
            if (level := logging.get("level")) and _env_not_set("LOG_LEVEL"):
                self.log_level = level


@lru_cache
def get_settings() -> AppSettings:
    """Get cached application settings.

    Returns:
        Cached AppSettings instance
    """
    return AppSettings()


def reset_settings() -> None:
    """Clear settings cache (for testing)."""
    get_settings.cache_clear()
